/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universityproject.IU;

import javax.swing.JOptionPane;
import universityproject.controlador.Controller;
import universityproject.model.Constant;
import universityproject.model.Department;

/**
 *
 * @author leand
 */
public class IUCadastroFuncionario extends javax.swing.JDialog {
     Controller control = new Controller();
    /**
     * Creates new form IUCadastroFuncionarios
     */
    public IUCadastroFuncionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        lb_teacher.setVisible(false);
        cb_teacher.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tb_codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tb_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tb_salario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cb_categoria = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cb_nivel = new javax.swing.JComboBox<>();
        lb_atributos = new javax.swing.JLabel();
        cb_atributos = new javax.swing.JComboBox<>();
        btn_salvar = new javax.swing.JButton();
        lb_teacher = new javax.swing.JLabel();
        cb_teacher = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        lb_locDepart = new javax.swing.JLabel();
        tb_codDepart = new javax.swing.JTextField();
        btn_locDdepart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro do Funcionario"));

        jLabel1.setText("Código");

        tb_codigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tb_codigoFocusLost(evt);
            }
        });
        tb_codigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_codigoMouseClicked(evt);
            }
        });
        tb_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_codigoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome");

        jLabel3.setText("Salário");

        jLabel5.setText("Categoria");

        cb_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Técnico", "Docente Efetivo", "Docente Substituto" }));
        cb_categoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cb_categoriaFocusLost(evt);
            }
        });
        cb_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_categoriaActionPerformed(evt);
            }
        });

        jLabel4.setText("Nível");

        cb_nivel.setEnabled(false);
        cb_nivel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cb_nivelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cb_nivelFocusLost(evt);
            }
        });
        cb_nivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_nivelActionPerformed(evt);
            }
        });

        lb_atributos.setText("Função");

        cb_atributos.setEnabled(false);

        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        lb_teacher.setText("label_especifico");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tb_salario, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tb_codigo))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(tb_name))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(64, 64, 64)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(cb_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_atributos)
                            .addComponent(cb_atributos, 0, 117, Short.MAX_VALUE)
                            .addComponent(lb_teacher)
                            .addComponent(cb_teacher, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(btn_salvar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(lb_atributos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_atributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lb_teacher, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cb_teacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_salvar)
                .addGap(54, 54, 54))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cabecalho"));

        lb_locDepart.setText("Código do  Departamento");

        tb_codDepart.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tb_codDepartFocusLost(evt);
            }
        });

        btn_locDdepart.setText("Localizar Departamento");
        btn_locDdepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_locDdepartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lb_locDepart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tb_codDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_locDdepart)
                .addGap(63, 63, 63))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_locDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_codDepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_locDdepart))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_categoriaActionPerformed
      
        int op = cb_categoria.getSelectedIndex();
        cb_nivel.removeAllItems();
        cb_atributos.removeAllItems();
        cb_teacher.removeAllItems();
        
        lb_teacher.setVisible(false);
        cb_teacher.setVisible(false);
        
        String atributos[];
   
        if (op == 0){
            atributos = Constant.funcao;
            lb_atributos.setText("Função");
            
            cb_nivel.addItem("T1");
            cb_nivel.addItem("T2");  
            
        } else if (op == 1){
            atributos = Constant.titulacao;
            String area[] = Constant.area;
            
            lb_atributos.setText("Titulação");
            
            cb_nivel.addItem("D1");
            cb_nivel.addItem("D2");
            cb_nivel.addItem("D3");
            
            for(int i=0; i < area.length; i++){
                cb_teacher.addItem(area[i]);
            }
            
            lb_teacher.setText("Área");
            lb_teacher.setVisible(true);
            cb_teacher.setVisible(true);
            
        } else {
            atributos = Constant.titulacao;
            int cargaHoraria[] = Constant.cargaHoraria;
            
            lb_atributos.setText("Titulacao");
            
            cb_nivel.addItem("S1");
            cb_nivel.addItem("S2");
            
            for(int i=0; i < cargaHoraria.length; i++){
                cb_teacher.addItem(Integer.toString(cargaHoraria[i]));
            }
            
            lb_teacher.setText("Carga Horária");
            lb_teacher.setVisible(true);
            cb_teacher.setVisible(true);

        }
        
        for(int i=0; i < atributos.length; i++){
            cb_atributos.addItem(atributos[i]);
        }
        
        cb_atributos.setEnabled(true);
        cb_nivel.setEnabled(true);
        
    }//GEN-LAST:event_cb_categoriaActionPerformed

    private void cb_nivelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cb_nivelFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_nivelFocusGained

    private void cb_categoriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cb_categoriaFocusLost
        
    }//GEN-LAST:event_cb_categoriaFocusLost

    private void cb_nivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_nivelActionPerformed
        
    }//GEN-LAST:event_cb_nivelActionPerformed

    private void cb_nivelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cb_nivelFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_nivelFocusLost

    private void tb_codigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb_codigoFocusLost
       
    }//GEN-LAST:event_tb_codigoFocusLost

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        String codeDepart = tb_codDepart.getText();
        
        if(control.searchDepartmentByCode(codeDepart) == null){
            JOptionPane.showMessageDialog(null, "Não existe um departamento com este código\nPor favor, insira um código válido");
            return;
        }
        String codigo = tb_codigo.getText();
        if(!control.searchEmployeeByCode(codigo).equals("")){
            JOptionPane.showMessageDialog(null, "Já existe um funcionário com este código\nPor favor, insira um código válido");
            return;
        }
        
        String nome = tb_name.getText();
        Double salario = Double.parseDouble(tb_salario.getText());
        String nivel = (String) cb_nivel.getSelectedItem();
        String atributo = (String) cb_atributos.getSelectedItem(); 
        
        int opCat = cb_categoria.getSelectedIndex();
        
        if(opCat == 0){
            control.addTechnician(codeDepart, codigo, nome, salario, nivel, atributo);
        } else if (opCat == 1){
            String area = (String) cb_teacher.getSelectedItem();
            control.addEffectiveTeacher(codeDepart, codigo, nome, salario, nivel, atributo, area);
        } else {
            int cargaHoraria = Integer.parseInt((String) cb_teacher.getSelectedItem());
            control.addSubstituteTeacher(codeDepart, codigo, nome, salario, nivel, atributo, cargaHoraria);
        }
        
        setVisible(false);
        
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void tb_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_codigoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tb_codigoActionPerformed

    private void tb_codigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_codigoMouseClicked
        
    }//GEN-LAST:event_tb_codigoMouseClicked

    private void btn_locDdepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_locDdepartActionPerformed
        IULocalizarDepartamentos localizar = new IULocalizarDepartamentos(null, true);
        localizar.setVisible(true);

        String codigo = localizar.getCodigo();
        Department d = control.searchDepartmentByCode(codigo);

        if (d != null){
            tb_codDepart.setText(d.getCode());
        }
    }//GEN-LAST:event_btn_locDdepartActionPerformed

    private void tb_codDepartFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb_codDepartFocusLost
        
    }//GEN-LAST:event_tb_codDepartFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IUCadastroFuncionario dialog = new IUCadastroFuncionario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_locDdepart;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JComboBox<String> cb_atributos;
    private javax.swing.JComboBox<String> cb_categoria;
    private javax.swing.JComboBox<String> cb_nivel;
    private javax.swing.JComboBox<String> cb_teacher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_atributos;
    private javax.swing.JLabel lb_locDepart;
    private javax.swing.JLabel lb_teacher;
    private javax.swing.JTextField tb_codDepart;
    private javax.swing.JTextField tb_codigo;
    private javax.swing.JTextField tb_name;
    private javax.swing.JTextField tb_salario;
    // End of variables declaration//GEN-END:variables
}
