/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universityproject.IU;

import universityproject.controlador.Controller;

/**
 *
 * @author leand
 */
public class IUPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form IUPrincipal
     */
    public IUPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem15 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MI_adddepartamentos = new javax.swing.JMenuItem();
        MI_addfuncionarios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MI_relatorios = new javax.swing.JMenu();
        MI_geral = new javax.swing.JMenuItem();
        MI_departamentos = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MI_funcGeral = new javax.swing.JMenuItem();
        MI_tecnicos = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        MI_docenGeral = new javax.swing.JMenuItem();
        MI_docenEfetivos = new javax.swing.JMenuItem();
        MI_docenSubstitutos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        jMenuItem15.setText("jMenuItem15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("University Project");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/universityproject.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jMenu1.setText("Cadastros");

        MI_adddepartamentos.setText("Departamento");
        MI_adddepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_adddepartamentosActionPerformed(evt);
            }
        });
        jMenu1.add(MI_adddepartamentos);

        MI_addfuncionarios.setText("Funcionario");
        MI_addfuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_addfuncionariosActionPerformed(evt);
            }
        });
        jMenu1.add(MI_addfuncionarios);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        jMenuItem5.setText("Departamento Específico");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem4.setText("Departamentos com Gasto em Faixa Específica");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);
        jMenu2.add(jSeparator1);

        jMenuItem10.setText("Funcionário pelo Código");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText("Funcionário pelo Nome");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem2.setText("Funcionários com Salário em Faixa Específica");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        MI_relatorios.setText("Relatorios");

        MI_geral.setText("Geral");
        MI_geral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_geralActionPerformed(evt);
            }
        });
        MI_relatorios.add(MI_geral);

        MI_departamentos.setText("Departamentos");
        MI_departamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_departamentosActionPerformed(evt);
            }
        });
        MI_relatorios.add(MI_departamentos);

        jMenu5.setText("Funcionarios");

        MI_funcGeral.setText("Geral");
        MI_funcGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_funcGeralActionPerformed(evt);
            }
        });
        jMenu5.add(MI_funcGeral);

        MI_tecnicos.setText("Técnicos");
        MI_tecnicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_tecnicosActionPerformed(evt);
            }
        });
        jMenu5.add(MI_tecnicos);

        jMenu6.setText("Docentes");

        MI_docenGeral.setText("Geral");
        MI_docenGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_docenGeralActionPerformed(evt);
            }
        });
        jMenu6.add(MI_docenGeral);

        MI_docenEfetivos.setText("Efetivos");
        MI_docenEfetivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_docenEfetivosActionPerformed(evt);
            }
        });
        jMenu6.add(MI_docenEfetivos);

        MI_docenSubstitutos.setText("Substitutos");
        MI_docenSubstitutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_docenSubstitutosActionPerformed(evt);
            }
        });
        jMenu6.add(MI_docenSubstitutos);

        jMenu5.add(jMenu6);

        MI_relatorios.add(jMenu5);

        jMenuBar1.add(MI_relatorios);

        jMenu4.setText("                                                                                                                        ");
        jMenuBar1.add(jMenu4);

        jMenu7.setText("Sair");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenu7MouseReleased(evt);
            }
        });
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MI_departamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_departamentosActionPerformed
        IURelatorio relatorio = new IURelatorio(this, false);
        Controller control = new Controller();
        relatorio.exibir("Relatório dos Departamentos", "Departamentos", control.resumeDepartment());
    }//GEN-LAST:event_MI_departamentosActionPerformed

    private void MI_geralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_geralActionPerformed
        IURelatorio relatorio = new IURelatorio(this, false);
        Controller control = new Controller();
        relatorio.exibir("Relatório Geral", "Geral", control.allData());
    }//GEN-LAST:event_MI_geralActionPerformed

    private void MI_funcGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_funcGeralActionPerformed
        IURelatorio relatorio = new IURelatorio(this, false);
        Controller control = new Controller();
        relatorio.exibir("Relatório Geral dos Funcionários", "Funcionários ", control.dataAllEmployee());
    }//GEN-LAST:event_MI_funcGeralActionPerformed

    private void MI_tecnicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_tecnicosActionPerformed
        IURelatorio relatorio = new IURelatorio(this, false);
        Controller control = new Controller();
        relatorio.exibir("Relatório dos Funcionários Técnicos", "Técnicos", control.dataAllTechnician());
    }//GEN-LAST:event_MI_tecnicosActionPerformed

    private void MI_docenEfetivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_docenEfetivosActionPerformed
        IURelatorio relatorio = new IURelatorio(this, false);
        Controller control = new Controller();
        relatorio.exibir("Relatório dos Docentes Efetivos", "Docentes Efetivos", control.dataAllEffectiveTeacher());
    }//GEN-LAST:event_MI_docenEfetivosActionPerformed

    private void MI_docenSubstitutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_docenSubstitutosActionPerformed
        IURelatorio relatorio = new IURelatorio(this, false);
        Controller control = new Controller();
        relatorio.exibir("Relatório dos Docentes Substitutos", "Docentes Substitutos", control.dataAllSubstituteTeacher());
    }//GEN-LAST:event_MI_docenSubstitutosActionPerformed

    private void MI_docenGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_docenGeralActionPerformed
        IURelatorio relatorio = new IURelatorio(this, false);
        Controller control = new Controller();
        relatorio.exibir("Relatório dos Docentes", "Docentes", control.dataAllTeacher());
    }//GEN-LAST:event_MI_docenGeralActionPerformed

    private void jMenu7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseReleased
        
    }//GEN-LAST:event_jMenu7MouseReleased

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenu7MouseClicked

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        IUConsulta consulta = new IUConsulta(this, false);
        Controller control = new Controller();
        consulta.exibir("Consulta", "Consulta de departamento por código");        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void MI_adddepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_adddepartamentosActionPerformed
        IUCadastroDepartamento cadastro = new IUCadastroDepartamento(this, true);
        cadastro.setVisible(true);
    }//GEN-LAST:event_MI_adddepartamentosActionPerformed

    private void MI_addfuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_addfuncionariosActionPerformed
        IUCadastroFuncionario cadastro = new IUCadastroFuncionario(this, true);
        cadastro.setVisible(true);
    }//GEN-LAST:event_MI_addfuncionariosActionPerformed


    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        IUConsulta consulta = new IUConsulta(this, false);
        Controller control = new Controller();
        consulta.exibir("Consulta", "Consulta de funcionário por código"); 
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        IUConsulta consulta = new IUConsulta(this, false);
        Controller control = new Controller();
        consulta.exibir("Consulta", "Consulta de funcionário por nome");
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        IUConsultaPorFaixa consulta = new IUConsultaPorFaixa(this, false);
        Controller control = new Controller();
        consulta.exibir("Consulta", "Consulta de departamento em faixa");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        IUConsultaPorFaixa consulta = new IUConsultaPorFaixa(this, false);
        Controller control = new Controller();
        consulta.exibir("Consulta", "Consulta de funcionário em faixa");
    }//GEN-LAST:event_jMenuItem2ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Controller control = new Controller();
        control.addDepartment("Matemática e Computação", "1", 30);
        control.addDepartment("Física", "2", 30);
        control.addDepartment("Química", "3", 10);
        control.addDepartment("Geografia", "4", 20);
        
        control.addTechnician("1", "1", "Renan", 1002.25, "T1", "Manutenção de computadores");
        control.addTechnician("1", "2", "Jorge", 1500.25, "T2", "Manutenção de rede");
        control.addEffectiveTeacher("1", "3", "Livia", 15000.30, "D1", "Doutor", "Visão Computacional");

        control.addTechnician("2", "4", "Marcos", 1500.25, "T2", "Manutenção dos laborátorios");
        control.addSubstituteTeacher("2", "5", "Felipe", 2000.5, "S1", "Mestre", 5);
        
        
        control.addTechnician("3", "6", "Carol", 1002.25, "T1", "Manutenção dos laborátorios");
        control.addSubstituteTeacher("3", "7", "Gabriel", 2500.5, "S2", "Mestre", 2);
        
        control.addEffectiveTeacher("4", "8", "Joana", 8000.40, "D2", "Doutor", "Ecologia");
        
        String relatorio = control.allData();
        System.out.println(relatorio);
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MI_adddepartamentos;
    private javax.swing.JMenuItem MI_addfuncionarios;
    private javax.swing.JMenuItem MI_departamentos;
    private javax.swing.JMenuItem MI_docenEfetivos;
    private javax.swing.JMenuItem MI_docenGeral;
    private javax.swing.JMenuItem MI_docenSubstitutos;
    private javax.swing.JMenuItem MI_funcGeral;
    private javax.swing.JMenuItem MI_geral;
    private javax.swing.JMenu MI_relatorios;
    private javax.swing.JMenuItem MI_tecnicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
